minor change

diff --git a/cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb b/cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
--- a/cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
+++ b/cookbooks/aws-parallelcluster-config/templates/default/init/fetch_and_run.erb
@@ -21,7 +21,7 @@ function error_exit () {
   script=`basename $0`
   echo "parallelcluster: ${script} - $1"
   logger -t parallelcluster "${script} - $1"
-  echo "${script} - $1" > /var/log/parallelcluster/bootstrap_error_msg
+  echo "$1. If --rollback-on-failure was set to false, check /var/log/cfn-init.log and /var/log/cloud-init-output.log for more details." > /var/log/parallelcluster/bootstrap_error_msg
   exit 1
 }
 
@@ -37,7 +37,7 @@ function download_run (){
     wget -qO- ${url} > $tmpfile || error_exit "Failed to run ${ACTION}, failed to download ${url} using wget, return code: $?"
   fi
   chmod +x $tmpfile || error_exit "Failed to run ${ACTION}, failed to run chmod +x ${tmpfile}, return code: $?"
-  $tmpfile "$@" || error_exit "Failed to run ${ACTION}, failed to execute file ${file}, return code: $?"
+  $tmpfile "$@" || error_exit "Failed to run ${ACTION}, ${file} failed with non 0 return code: $?"
 }
 
 function get_stack_status () {
